apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loaduqfh2985-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loaduqfh2985-tenant-component
    app.kubernetes.io/part-of: loaduqfh2985-tenant-app
  name: loaduqfh2985-tenant-component
  namespace: loaduqfh2985-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loaduqfh2985-tenant-component
status:
  loadBalancer: {}
